# Generated by Django 4.1.2 on 2022-10-31 06:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_widhlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='widhlist',
            new_name='wishlist',
        ),
    ]
